FROM node:16-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY ./package.json ./package-lock.json* ./

COPY . .

RUN npm install

RUN npm run build

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ARG TWITTER_API_KEY

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

EXPOSE 3000

ENV PORT 3000
ENV TWITTER_API_KEY ${TWITTER_API_KEY}

CMD ["npm", "run" ,"start"]