FROM node:16-alpine

RUN apk add --no-cache libc6-compat
ARG TWITTER_API_KEY

WORKDIR /app

COPY ./package.json ./package-lock.json* ./

COPY . .

RUN npm install

ENV TWITTER_API_KEY $TWITTER_API_KEY
RUN npm run build

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run" ,"start"]